version: '3.5'

services:
  web:
    build: ./src
    environment:
      - DJANGO_TIMEZONE=$DJANGO_TIMEZONE
      - DJANGO_DEBUG=$DJANGO_DEBUG
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
      - DJANGO_STATIC=$DJANGO_STATIC
      - DJANGO_MEDIA=$DJANGO_MEDIA
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_NAME=$MYSQL_NAME
      - MYSQL_PWD=$MYSQL_PWD
    volumes:
      - ./src/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8000:8000

volumes:
  static_volume:
